### PR TITLE
Fix Travis tests

### PR DESCRIPTION
**Pull request by sarina**
## Tests Are Important!
- Fix Travis build errors
- Add myself and @louyihua to AUTHORS

### CODE REVIEW

**Comment by sarina** [comment]
@EnTeQuAk Got your Travis stuff cleared up, and put a test badge on your README.

Happy to help with getting coverage testing and badging set up, if you're interested.

**Comment by EnTeQuAk** [comment]
Wow, amazing work, thank you so much!

Sure, help is always appreciated, tests might be the one thing but I think what markey is lacking would be docs. So if you're up for it feel free to start writing some docs and simple examples, e.g how you're using it etc.

**Comment by sarina** [comment]
Frankly, we're only using this as a part of django_babel_underscore, but as it's a critical part of our infrastructure - and markey is a critical part of that! - I'm invested in making sure this repo works well.

If I can drum up some spare time I will see what I can do about docs on both repos.

**Comment by EnTeQuAk** [comment]
I see, fair enough and thank you so much for the contributions!

May I ask where and how specifically you're using django-babel-underscore? Always nice to see how it's being used apart from my own stuff.

Please let me know if there's anything I can help with or at least give some feedback. Also let me know if you're working on something before the weekend, else I'd try to sprint on various stuff and open pull requests to get feedback. Writing docs for a parser-framework is challenging :smile: 

Again, thanks a lot!

**Comment by sarina** [comment]
We're using this in edx-platform, which is an online open source educational platform.

https://github.com/edx/edx-platform
https://open.edx.org/

Particularly we use Underscore templates and needed a way to i18n them, and there's not much out there! We have a PR open against django-babel-underscore to incorporate the tokenizing work from #3, and I'm working on your Travis tests there as well, but no other work planned right now.

Is there anything more I can do on this particular PR or can it be merged? If I have time for docs, I can do that in another PR.

**Comment by sarina** [comment]
@EnTeQuAk - is there anything more that I can do to get this specific PR merged? I totally get you want more documentation but I likely won't have time to get to that for a while, as I'm leaving edX soon and will be strapped for time for the next few months.

I'm happy to respond to specific requests on this PR that will get it merged.

**Comment by EnTeQuAk** [comment]
Merged, apologies. I totally forgot about this one :o

Thanks a lot! :cake: :star2: :rocket:

**Comment by sarina** [comment]
No worries, thanks!

**Pull request merged**
