### PR TITLE
Prepare for 0.8

### PR DESCRIPTION
**Pull request by sarina**
@EnTeQuAk I've done you the courtesy of doing as much as I can to release a new version (since the merge of https://github.com/EnTeQuAk/django-babel-underscore/pull/4 is relying on the next version of this library!)

### CODE REVIEW

**Comment by sarina** [comment]
cc @louyihua & @kosmos342 - did I represent your contributions properly?

**Comment by louyihua** [comment]
It's fine to me :)

**Comment by kosmos342** [comment]
+

**Comment by EnTeQuAk** [comment]
Sorry for the very late reply on this, I'm about to do a new release right now.

**Comment by sarina** [comment]
yay!

**Pull request merged**
